name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.BLOG_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "contact@mail.ruofei.site"
          git config --global user.name "ruofei"
          npm install hexo-cli yarn -g
          yarn

      - name: Deploy 2 Github Pages (repo - smpower.github.io)
        run: |
          hexo clean
          hexo deploy

      - name: Deploy 2 vercel
        run: |
        curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_jvK46JFFF8UCRDL3ajLZWzN5USGz/mPfwYBtppT
      
      # - name: Depoly 2 tcb # Tencent Cloudbase
      #   run: |
      #     yarn tcb login --apiKeyId AKID96JRM41IeT9cv0s0IMfnj06MeCZ9Knxu --apiKey zOnVaCpbSTOBmCRUt2AVmCWzPeebU9Zf
      #     yarn tcb hosting deploy ./public -e hexo-blog-1gqvz4yy54676e17
