name: Auto Hexo Deploy From Wiki Repo

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy project
        run: |
          pwd
          ls ../ -al
          cp -rfv ../hi-ruofei.com ../tmp
          ls ../ -al
